language: python
sudo: required
os: linux
notifications:
  email: 
    - bastien.lecussan@epitech.eu
    - charles.aubert@epitech.eu
    - nicolas.gascon@epitech.eu
python:
  - "3.6"
services:
  - docker

before_install:
  - docker-compose build

script:
  - docker-compose up test