language: python
sudo: required
os: linux
notifications:
  email:
    recipients:
      - nicolas1.moreel-lebon@epitech.eu
    on_success: always
    on_failure: always
python:
  - "3.6"
services:
  - docker

before_install:
  - docker-compose build

script:
  - docker-compose up test