language: python
sudo: required
os: linux
notifications:
  email: false
python:
  - "3.6"
services:
  - postgresql
install:
  - pip install -r requirements.txt
before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres
script:
  - python manage.py test