version: '3'

services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
  api:
    build: .
    command: bash -c "python manage.py test && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: todolist_api
    volumes:
      - .:/api/
    ports:
      - "8000:8000"
    links:
      - db:db
    depends_on:
      - db
