version: '3'

services:
  db:
    image: nouchka/sqlite3
  api:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: todolist_api
    volumes:
      - .:/api/
    ports:
      - "8000:8000"
    links:
      - db:db