version: '3'

services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
  test:
    build: .
    command: bash -c "./wait-for-it.sh db:5432 -- python manage.py test"
    container_name: todolist_api_test
    links:
      - db:db
    depends_on:
      - db
  api:
    build: .
    command: bash -c "./wait-for-it.sh db:5432 -- python manage.py makemigrations api_v1 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: todolist_api
    volumes:
      - .:/api/
    ports:
      - "8000:8000"
    links:
      - db:db
    depends_on:
      - db
